"""add_property_parent_and_budget_distributable

Revision ID: 1eeaa9fd274c
Revises: 
Create Date: 2026-03-06 14:45:42.901581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eeaa9fd274c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_distributable', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_properties_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key('fk_property_parent', 'properties', ['parent_id'], ['id'])
    
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_property_id'), ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_property_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_parent_id'), table_name='properties')
    op.drop_column('properties', 'parent_id')
    op.drop_column('budget_categories', 'is_distributable')
    # ### end Alembic commands ###
