"""add_invoices_and_reconciliation

Revision ID: 20c62981c3ae
Revises: f7a8b9c0d1e2
Create Date: 2026-03-28 12:33:46.655715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c62981c3ae'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('Pendiente', 'Pagada', 'Vencida', 'Anulada', name='invoicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_property_id'), ['property_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('is_reconciled', sa.Boolean(create_constraint=False), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_transactions_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_foreign_key('fk_tx_invoice_id', 'invoices', ['invoice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tx_invoice_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_invoice_id'))
        batch_op.drop_column('is_reconciled')
        batch_op.drop_column('invoice_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_property_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_contract_id'))

    op.drop_table('invoices')
    # ### end Alembic commands ###
