"""Add BudgetRevision model

Revision ID: 35062d0fae50
Revises: 596d7c54cff9
Create Date: 2026-03-20 19:10:04.366880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35062d0fae50'
down_revision: Union[str, None] = '596d7c54cff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('budget_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('old_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('new_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_revisions_budget_id'), ['budget_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_revisions_budget_id'))

    op.drop_table('budget_revisions')
    # ### end Alembic commands ###
