"""Add budget_category_id to transactions

Revision ID: 39a4751a1d99
Revises: cd90fe03f433
Create Date: 2026-03-20 15:36:39.338147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a4751a1d99'
down_revision: Union[str, None] = 'cd90fe03f433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_category_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_budget_category_id'), ['budget_category_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_budget_category_id', 'budget_categories', ['budget_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_budget_category_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_budget_category_id'))
        batch_op.drop_column('budget_category_id')

    # ### end Alembic commands ###
