"""budget_projects_new

Revision ID: 47d904c6237f
Revises: 7a25039f37da
Create Date: 2026-03-29 19:13:36.632055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d904c6237f'
down_revision: Union[str, None] = '7a25039f37da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('budget_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.Enum('Mantenimiento', 'Mejora', 'Remodelación', 'Otro', name='projecttype'), nullable=False),
    sa.Column('status', sa.Enum('Borrador', 'Cotizando', 'Aprobado', 'En Ejecución', 'Completado', 'Cancelado', name='projectstatus'), nullable=False),
    sa.Column('priority', sa.Enum('Urgente', 'Alta', 'Media', 'Baja', name='projectpriority'), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('approved_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('approved_quote_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_start', sa.Date(), nullable=True),
    sa.Column('scheduled_end', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_projects_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_projects_property_id'), ['property_id'], unique=False)

    op.create_table('project_quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('quote_file', sa.String(length=500), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['budget_projects.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_quotes_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_quotes_project_id'))

    op.drop_table('project_quotes')
    with op.batch_alter_table('budget_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_projects_property_id'))
        batch_op.drop_index(batch_op.f('ix_budget_projects_budget_id'))

    op.drop_table('budget_projects')
    # ### end Alembic commands ###
