"""add_administration_fee_to_property

Revision ID: 52cb2eaf2e99
Revises: a2b3c4d5e6f7
Create Date: 2026-03-07 18:34:17.240464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cb2eaf2e99'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_budget_categories')
    op.drop_index('ix_inspections_property_id', table_name='inspections')
    op.drop_table('inspections')
    op.drop_index('ix_assets_property_id', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_property_occupants_property_id', table_name='property_occupants')
    op.drop_table('property_occupants')
    op.add_column('budgets', sa.Column('auto_calculate_total', sa.Boolean(), nullable=False))
    op.add_column('properties', sa.Column('administration_fee', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'properties', 'properties', ['parent_id'], ['id'])
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_property_id'), 'transactions', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_property_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'administration_fee')
    op.drop_column('budgets', 'auto_calculate_total')
    op.create_table('property_occupants',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('property_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('dni', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_property_occupants_property_id', 'property_occupants', ['property_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('property_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=17), nullable=False),
    sa.Column('purchase_date', sa.DATE(), nullable=True),
    sa.Column('warranty_expiry', sa.DATE(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_property_id', 'assets', ['property_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('property_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inspection_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('scheduled_date', sa.DATE(), nullable=False),
    sa.Column('completed_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('inspector_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('findings', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspections_property_id', 'inspections', ['property_id'], unique=False)
    op.create_table('_alembic_tmp_budget_categories',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('budget_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('budgeted_amount', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('executed_amount', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_distributable', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
