"""Add budget closure fields

Revision ID: 596d7c54cff9
Revises: 52a1b941d3ce
Create Date: 2026-03-20 15:56:45.336435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596d7c54cff9'
down_revision: Union[str, None] = '52a1b941d3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('frozen_distribution', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_column('frozen_distribution')
        batch_op.drop_column('is_closed')

    # ### end Alembic commands ###
