"""Add transaction status and budget category account

Revision ID: 85e953827813
Revises: 35062d0fae50
Create Date: 2026-03-21 10:24:58.567958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e953827813'
down_revision: Union[str, None] = '35062d0fae50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.Enum('Corriente', 'Ahorros', 'Inversión', 'Caja Menor', name='accounttype'), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_type', sa.Enum('Proveedor', 'Cliente', 'Arrendatario', 'Otro', name='contacttype'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Propietario', 'Gestor', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('work_group_id', sa.String(length=36), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['work_group_id'], ['work_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_work_group_id'), ['work_group_id'], unique=False)

    op.create_table('work_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('super_admin_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['super_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_groups_super_admin_id'), ['super_admin_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('work_group_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_group_id'], ['work_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_work_group_id'), ['work_group_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('Vencimiento', 'Presupuesto', 'Contrato', 'Pago', 'Mantenimiento', 'Sistema', name='notificationtype'), nullable=False),
    sa.Column('level', sa.Enum('Info', 'Warning', 'Critical', name='notificationlevel'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('property_type', sa.Enum('Apartamento', 'Casa', 'Local', 'Bodega', 'Oficina', 'Lote', 'Otros', name='propertytype'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('cadastral_id', sa.String(length=50), nullable=True),
    sa.Column('commercial_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('administration_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pays_administration', sa.Boolean(), nullable=False),
    sa.Column('administration_day', sa.Integer(), nullable=True),
    sa.Column('administration_payment_method', sa.String(length=100), nullable=True),
    sa.Column('administration_payment_info', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Disponible', 'Arrendada', 'En Mantenimiento', 'Vendida', name='propertystatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('has_insurance', sa.Boolean(), nullable=False),
    sa.Column('risk_score_avg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('telegram_unit_id', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_parent_id'), ['parent_id'], unique=False)

    op.create_table('work_group_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Super Admin', 'Analista', name='workgrouprole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_group_id'], ['work_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_group_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_group_members_work_group_id'), ['work_group_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('Operativo', 'En Reparación', 'Fuera de Servicio', 'Dado de Baja', name='assetstatus'), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_property_id'), ['property_id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.Enum('Mensual', 'Bimestral', 'Trimestral', 'Semestral', 'Anual', name='budgetperiod'), nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_executed', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('auto_calculate_total', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('frozen_distribution', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_property_id'), ['property_id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_name', sa.String(length=200), nullable=False),
    sa.Column('tenant_email', sa.String(length=255), nullable=True),
    sa.Column('tenant_phone', sa.String(length=20), nullable=True),
    sa.Column('tenant_document', sa.String(length=50), nullable=True),
    sa.Column('contract_type', sa.Enum('Vivienda', 'Comercial', 'Garaje', name='contracttype'), nullable=False),
    sa.Column('monthly_rent', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('auto_renewal', sa.Boolean(), nullable=False),
    sa.Column('annual_increment_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('Borrador', 'Enviado a Firma', 'Firmado', 'Activo', 'Finalizado', 'Cancelado', name='contractstatus'), nullable=False),
    sa.Column('pdf_file', sa.String(length=500), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_ip', sa.String(length=45), nullable=True),
    sa.Column('signature_hash', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_property_id'), ['property_id'], unique=False)

    op.create_table('inspections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('inspection_type', sa.Enum('Preventiva', 'Entrega', 'Recibo', 'Rutinaria', name='inspectiontype'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('Programada', 'Realizada', 'Cancelada', name='inspectionstatus'), nullable=False),
    sa.Column('inspector_name', sa.String(length=200), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_property_id'), ['property_id'], unique=False)

    op.create_table('maintenance_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('maintenance_type', sa.Enum('Correctivo', 'Preventivo', 'Mejora', name='maintenancetype'), nullable=False),
    sa.Column('status', sa.Enum('Pendiente', 'En Progreso', 'Esperando Factura', 'Completado', 'Cancelado', name='maintenancestatus'), nullable=False),
    sa.Column('priority', sa.Enum('Urgente', 'Alta', 'Media', 'Baja', name='maintenancepriority'), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('invoice_file', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('source', sa.Enum('Manual', 'Telegram', name='maintenancesource'), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_message_id', sa.String(length=100), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_orders_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('property_occupants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('dni', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_occupants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_occupants_property_id'), ['property_id'], unique=False)

    op.create_table('tenant_scorings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_name', sa.String(length=200), nullable=False),
    sa.Column('tenant_document', sa.String(length=50), nullable=True),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('alerts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_group_properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_group_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['work_group_id'], ['work_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_group_properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_group_properties_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_group_properties_work_group_id'), ['work_group_id'], unique=False)

    op.create_table('budget_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('budget_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('budgeted_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('executed_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_distributable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_categories_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_categories_budget_id'), ['budget_id'], unique=False)

    op.create_table('budget_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('budget_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('old_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('new_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_revisions_budget_id'), ['budget_id'], unique=False)

    op.create_table('contract_signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('signer_name', sa.String(length=200), nullable=False),
    sa.Column('signer_document', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('signature_hash', sa.String(length=256), nullable=True),
    sa.Column('signed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_signatures_contract_id'), ['contract_id'], unique=False)

    op.create_table('insurance_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('insurer', sa.String(length=200), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('coverage_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Vigente', 'Vencida', 'Cancelada', name='policystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_policies_contract_id'), ['contract_id'], unique=False)

    op.create_table('maintenance_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=200), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['maintenance_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_photos_order_id'), ['order_id'], unique=False)

    op.create_table('payment_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('Pendiente', 'Pagado', 'Vencido', name='paymentstatus'), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_schedules_contract_id'), ['contract_id'], unique=False)

    op.create_table('property_inventories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=True),
    sa.Column('inventory_type', sa.Enum('Ingreso', 'Salida', 'Verificación', name='inventorytype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_inventories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_inventories_property_id'), ['property_id'], unique=False)

    op.create_table('termination_letters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('termination_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_termination_letters_contract_id'), ['contract_id'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inventory_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('condition', sa.Enum('Excelente', 'Bueno', 'Regular', 'Malo', 'No Aplica', name='itemcondition'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['property_inventories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_inventory_id'), ['inventory_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('budget_category_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_type', sa.Enum('Ingreso', 'Gasto', 'Transferencia', 'Ajuste', 'Interés', 'Abono', 'Crédito', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('Pendiente', 'Completada', 'Cancelada', name='transactionstatus'), server_default='Completada', nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('direction', sa.Enum('Debit', 'Credit', name='transactiondirection'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('invoice_file', sa.String(length=500), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('work_group_id', sa.String(length=36), nullable=True),
    sa.Column('audit_log_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], ),
    sa.ForeignKeyConstraint(['budget_category_id'], ['budget_categories.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_group_id'], ['work_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_budget_category_id'), ['budget_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_work_group_id'), ['work_group_id'], unique=False)

    op.create_table('inventory_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inventory_item_id', sa.String(length=36), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_photos_inventory_item_id'), ['inventory_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_photos_inventory_item_id'))

    op.drop_table('inventory_photos')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_work_group_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_property_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_budget_category_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_inventory_id'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('termination_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_termination_letters_contract_id'))

    op.drop_table('termination_letters')
    with op.batch_alter_table('property_inventories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_inventories_property_id'))

    op.drop_table('property_inventories')
    with op.batch_alter_table('payment_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_schedules_contract_id'))

    op.drop_table('payment_schedules')
    with op.batch_alter_table('maintenance_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_photos_order_id'))

    op.drop_table('maintenance_photos')
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_policies_contract_id'))

    op.drop_table('insurance_policies')
    with op.batch_alter_table('contract_signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_signatures_contract_id'))

    op.drop_table('contract_signatures')
    with op.batch_alter_table('budget_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_revisions_budget_id'))

    op.drop_table('budget_revisions')
    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_categories_budget_id'))
        batch_op.drop_index(batch_op.f('ix_budget_categories_account_id'))

    op.drop_table('budget_categories')
    with op.batch_alter_table('work_group_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_group_properties_work_group_id'))
        batch_op.drop_index(batch_op.f('ix_work_group_properties_property_id'))

    op.drop_table('work_group_properties')
    op.drop_table('tenant_scorings')
    with op.batch_alter_table('property_occupants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_occupants_property_id'))

    op.drop_table('property_occupants')
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_orders_property_id'))

    op.drop_table('maintenance_orders')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_property_id'))

    op.drop_table('inspections')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_property_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_property_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_property_id'))

    op.drop_table('assets')
    with op.batch_alter_table('work_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_group_members_work_group_id'))
        batch_op.drop_index(batch_op.f('ix_work_group_members_user_id'))

    op.drop_table('work_group_members')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_parent_id'))
        batch_op.drop_index(batch_op.f('ix_properties_owner_id'))

    op.drop_table('properties')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_work_group_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('work_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_groups_super_admin_id'))

    op.drop_table('work_groups')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_work_group_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('global_configs')
    op.drop_table('contacts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
