"""add_initial_balance_to_bank_account

Revision ID: 8daf6587116c
Revises: 984c5ebb5f65
Create Date: 2026-03-29 09:47:48.265716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8daf6587116c'
down_revision: Union[str, None] = '984c5ebb5f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_balance', sa.Numeric(precision=15, scale=2), nullable=False))

    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('Pendiente', 'Esperando Cotizacion', 'Esperando Aprobacion', 'En Progreso', 'Esperando Factura', 'Completado', 'Cancelado', name='maintenancestatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Pendiente', 'Esperando Cotizacion', 'Esperando Aprobacion', 'En Progreso', 'Esperando Factura', 'Completado', 'Cancelado', name='maintenancestatus'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=False)

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('initial_balance')

    # ### end Alembic commands ###
