"""Add bank account investment fields

Revision ID: 9734b754dad2
Revises: eeafbb0c819b
Create Date: 2026-04-18 18:54:07.190833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9734b754dad2'
down_revision: Union[str, None] = 'eeafbb0c819b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_investment', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('interest_periodicity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('maturity_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_interest_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('last_interest_date')
        batch_op.drop_column('maturity_date')
        batch_op.drop_column('interest_periodicity')
        batch_op.drop_column('interest_rate')
        batch_op.drop_column('is_investment')

    # ### end Alembic commands ###
