"""suppliers_quotes

Revision ID: 984c5ebb5f65
Revises: 20c62981c3ae
Create Date: 2026-03-28 13:21:13.282736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984c5ebb5f65'
down_revision: Union[str, None] = '20c62981c3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        # column was already added during previous failed migration
        # batch_op.add_column(sa.Column('specialty', sa.String(length=100), nullable=True))
        pass

    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_file', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_maintenance_approved_by', 'users', ['approved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_maintenance_approved_by', type_='foreignkey')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('quote_file')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###
