"""Add WorkGroups and AuditLogs

Revision ID: acbbf360050f
Revises: a2b3c4d5e6f7
Create Date: 2026-03-09 16:58:34.903096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbbf360050f'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('super_admin_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['super_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_groups_super_admin_id'), ['super_admin_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('work_group_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_group_id'], ['work_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_work_group_id'), ['work_group_id'], unique=False)

    op.create_table('work_group_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Super Admin', 'Analista', name='workgrouprole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_group_id'], ['work_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_group_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_group_members_work_group_id'), ['work_group_id'], unique=False)

    op.create_table('work_group_properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_group_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['work_group_id'], ['work_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_group_properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_group_properties_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_group_properties_work_group_id'), ['work_group_id'], unique=False)

    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Enum('Manual', 'Telegram', name='maintenancesource'), server_default='Manual', nullable=False))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telegram_message_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_photos', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_insurance', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('risk_score_avg', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('telegram_unit_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_properties_parent_id_properties', 'properties', ['parent_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_group_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('audit_log_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_work_group_id'), ['work_group_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_audit_log_id_audit_logs', 'audit_logs', ['audit_log_id'], ['id'])
        batch_op.create_foreign_key('fk_transactions_work_group_id_work_groups', 'work_groups', ['work_group_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_group_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_work_group_id'), ['work_group_id'], unique=False)
        batch_op.create_foreign_key('fk_users_work_group_id_work_groups', 'work_groups', ['work_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_work_group_id_work_groups', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_work_group_id'))
        batch_op.drop_column('login_attempts')
        batch_op.drop_column('last_login')
        batch_op.drop_column('work_group_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_audit_log_id_audit_logs', type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_work_group_id_work_groups', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_work_group_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_property_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('audit_log_id')
        batch_op.drop_column('work_group_id')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_properties_parent_id_properties', type_='foreignkey')
        batch_op.drop_column('telegram_unit_id')
        batch_op.drop_column('risk_score_avg')
        batch_op.drop_column('has_insurance')

    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('has_photos')
        batch_op.drop_column('telegram_message_id')
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('work_group_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_group_properties_work_group_id'))
        batch_op.drop_index(batch_op.f('ix_work_group_properties_property_id'))

    op.drop_table('work_group_properties')
    with op.batch_alter_table('work_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_group_members_work_group_id'))
        batch_op.drop_index(batch_op.f('ix_work_group_members_user_id'))

    op.drop_table('work_group_members')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_work_group_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('work_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_groups_super_admin_id'))

    op.drop_table('work_groups')
    # ### end Alembic commands ###
