"""Add InsurancePolicy table

Revision ID: c5c3f056f573
Revises: e89d35b1f6fd
Create Date: 2026-03-09 17:10:54.286311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c3f056f573'
down_revision: Union[str, None] = 'e89d35b1f6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
