"""Add signature fields to Contract

Revision ID: e89d35b1f6fd
Revises: acbbf360050f
Create Date: 2026-03-09 17:05:59.737236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89d35b1f6fd'
down_revision: Union[str, None] = 'acbbf360050f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('signed_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('signature_hash', sa.String(length=255), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('Borrador', 'Enviado a Firma', 'Firmado', 'Activo', 'Finalizado', 'Cancelado', name='contractstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Borrador', 'Enviado a Firma', 'Firmado', 'Activo', 'Finalizado', 'Cancelado', name='contractstatus'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('signature_hash')
        batch_op.drop_column('signed_ip')
        batch_op.drop_column('signed_at')

    # ### end Alembic commands ###
