"""add_amenities_to_property

Revision ID: edf51d06a3ce
Revises: 85e953827813
Create Date: 2026-03-23 10:23:23.819519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf51d06a3ce'
down_revision: Union[str, None] = '85e953827813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_parking', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('has_elevator', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('has_pool', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('has_gym', sa.Boolean(), nullable=False))
        batch_op.drop_column('risk_score_avg')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_score_avg', sa.NUMERIC(precision=5, scale=2), nullable=True))
        batch_op.drop_column('has_gym')
        batch_op.drop_column('has_pool')
        batch_op.drop_column('has_elevator')
        batch_op.drop_column('has_parking')

    # ### end Alembic commands ###
