"""Add budget_project_id to MaintenanceOrder

Revision ID: eeafbb0c819b
Revises: 47d904c6237f
Create Date: 2026-04-04 19:20:24.603602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeafbb0c819b'
down_revision: Union[str, None] = '47d904c6237f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_project_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_maintenance_orders_budget_project_id'), ['budget_project_id'], unique=False)
        batch_op.create_foreign_key(None, 'budget_projects', ['budget_project_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_maintenance_orders_budget_project_id'))
        batch_op.drop_column('budget_project_id')

    # ### end Alembic commands ###
